#!/usr/bin/env python3.6
# flake8:noqa
# isort:skip_file

import sys

if sys.version_info < (3,6):
    sys.exit('Sorry, Python < 3.6 is not supported')

from fuku.client import Client
from fuku.session import Session
# from fuku.configuration import Configuration
from fuku.profile import Profile
from fuku.region import Region
from fuku.cluster import Cluster
from fuku.node import Node, EcsNode
from fuku.app import App, EcsApp
from fuku.image import Image
from fuku.task import Task
from fuku.service import Service, EcsService
# from fuku.app import App
# from fuku.machine import Machine
# from fuku.image import Image
# from fuku.task import Task
# from fuku.service import Service
# # from fuku.container import Container
from fuku.pg import Pg
# from fuku.ssl import SSL
from fuku.redis import Redis, EcsRedis
from fuku.metrics import Metrics
from fuku.datadog import Datadog
# from fuku.papertrail import Papertrail


if __name__ == '__main__':
    cli = Client()
    cli.add_modules(
        Session,
        Profile, Region,
        Cluster, EcsNode,
        EcsApp,
        Image, Task, EcsService,
        EcsRedis, Pg,
        Metrics,
        Datadog
    )
    cli.entry()
